# Reference: https://www.digitalocean.com/community/tutorials/how-to-build-a-node-js-application-with-docker
# Ref: https://ashwin9798.medium.com/nginx-with-docker-and-node-js-a-beginners-guide-434fe1216b6b
# Ref: https://www.digitalocean.com/community/tutorials/how-to-secure-a-containerized-node-js-application-with-nginx-let-s-encrypt-and-docker-compose
FROM node:16-alpine AS builder
ADD https://github.com/ufoscout/docker-compose-wait/releases/download/2.2.1/wait /wait
RUN mkdir -p /home/node/app/node_modules && chown -R node:node /home/node/app /wait

WORKDIR /home/node/app

COPY package*.json yarn.lock  ./

RUN yarn install --pure-lockfile --production
COPY . .

EXPOSE 3010

CMD ["yarn", "build-start"]
